sudo: false

addons:
  apt: # install dependencies
    update: true
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - unzip
    - expect
    - powershell
  
install: # install apama
  - wget https://downloads.apamacommunity.com/apama/10.2.0.1/apama_10.2.0.1_amd64_linux.zip  -O /tmp/apama.zip
  - unzip /tmp/apama.zip -d /tmp/
  - ./travis-scripts/install-apama-prompts
  
before_script: # add various apama utils to the path (eg. engine_deploy)
  - source ./softwareag/Apama/bin/apama_env
  
script: 
  # Build the project
  - ./build.ps1 -sagInstallDir ./softwareag -forTest
  # Test the project
  - ./travis-scripts/test-with-exitcode