#!/usr/bin/expect -f

spawn /tmp/apama_10.2.0.1_amd64_linux/install -installDir $::env(PWD)/softwareag
expect "Enter:"
send "\n"
expect "Installation directory:"
send "\n"
expect "Host name or IP address:"
send "\n"
expect "Enter:"
send "\n"
expect "Enter:"
send "\n"
expect "Enter:"
send "\n"
expect "Press enter to continue"
send "\n"
expect "I have read and I agree to the terms of the license agreements shown above."
send "Y\n"
expect "Enter:"
send "\n"
expect "License file:"
send "\n"
expect "Work directory:"
send "$::env(PWD)/apama-work\n"
expect "Enter:"
send "\n"
expect "Enter:"
send "\n"
expect "Enter:"
send "\n"
interact