#!/usr/bin/expect -f

spawn /bin/bash -c {cd test; expect -c 'spawn pysys run -vCRIT; interact' | grep -v ":pysys:" && exit ${PIPESTATUS[0]}}
set timeout -1
log_user 0
expect " unsupported hash type sha512"
log_user 1
expect {
	"THERE WERE NO NON PASSES" { 
		expect eof
		puts "The tests PASSED"
		exit 0
	}
	"BLOCKED" {
		expect eof
		puts "The tests BLOCKED"
		exit 1
	}
	"TIMED OUT" {
		expect eof
		puts "The tests TIMED OUT"
		exit 1
	}
	"FAILED" {
		expect eof
		puts "The tests FAILED"
		exit 1
	}
	oef { 
		puts "The tests finished unexpectedly"
		exit 1
	}
}
puts "The tests finished unexpectedly"
exit 1